// Datos reales transcritos de ATLAS_C6_Base_Datos_Dashboard.xlsx
// Fuente primaria: docProps/core.xml -> "Datos consolidados de investigaciones INV-001 a INV-008"
// Regla del brief: no se crean datos ni se completan valores faltantes.
// Año null = "Año no determinado" en el XLSX (código -1).

export const VALIDACION = [
  ['Residentes de Comuna 6', 28, 100, 'Muestra', 'Todos los 28 declararon vivir en Comuna 6.'],
  ['Buscan por familiares, amigos o vecinos', 19, 67.9, 'Canales de descubrimiento', 'Canal de descubrimiento reportado.'],
  ['Facebook', 10, 35.7, 'Canales de descubrimiento', 'Canal de descubrimiento reportado.'],
  ['Instagram', 9, 32.1, 'Canales de descubrimiento', 'Canal de descubrimiento reportado.'],
  ['Google / buscador', 9, 32.1, 'Canales de descubrimiento', 'Canal de descubrimiento reportado.'],
  ['Google Maps', 8, 28.6, 'Canales de descubrimiento', 'Canal de descubrimiento reportado.'],
  ['Buscan restaurantes y alimentación', 18, 64.3, 'Tipo de oferta buscada', 'Tipo de oferta buscada.'],
  ['Buscan tiendas y comercios', 17, 60.7, 'Tipo de oferta buscada', 'Tipo de oferta buscada.'],
  ['Información no parece actualizada', 12, 42.9, 'Dificultades', 'Dificultad reportada.'],
  ['No encuentran suficientes opciones', 10, 35.7, 'Dificultades', 'Dificultad reportada.'],
  ['No encuentran precios', 7, 25, 'Dificultades', 'Dificultad reportada.'],
  ['No saben dónde buscar', 5, 17.9, 'Dificultades', 'Dificultad reportada.'],
  ['No encuentran dirección exacta', 5, 17.9, 'Dificultades', 'Dificultad reportada.'],
  ['No pueden comparar fácilmente', 5, 17.9, 'Dificultades', 'Dificultad reportada.'],
  ['Generalmente no presentan dificultades', 5, 17.9, 'Dificultades', 'Respuesta de contraste.'],
  ['Ubicación importante para decidir', 17, 60.7, 'Información para decidir', 'Información considerada importante.'],
  ['Precios importantes para decidir', 17, 60.7, 'Información para decidir', 'Información considerada importante.'],
  ['Horarios importantes para decidir', 14, 50, 'Información para decidir', 'Información considerada importante.'],
  ['Productos / servicios importantes', 13, 46.4, 'Información para decidir', 'Información considerada importante.'],
  ['Disponibilidad importante', 12, 42.9, 'Información para decidir', 'Información considerada importante.'],
  ['Distancia importante', 12, 42.9, 'Información para decidir', 'Información considerada importante.'],
  ['Conocen actores locales poco conocidos fuera del barrio', 20, 71.4, 'Conocimiento de oferta local', 'Indicador de conocimiento de oferta local.'],
  ['Consideran útil un sistema integrado', 26, 92.9, 'Utilidad del sistema', 'Algo o muy útil.'],
  ['Buscar escribiendo lo que necesito', 20, 71.4, 'Funcionalidades priorizadas', 'Funcionalidad priorizada.'],
  ['Teléfono / WhatsApp', 15, 53.6, 'Funcionalidades priorizadas', 'Funcionalidad / información priorizada.'],
  ['Buscar por barrio', 13, 46.4, 'Funcionalidades priorizadas', 'Funcionalidad priorizada.'],
  ['Horarios', 12, 42.9, 'Funcionalidades priorizadas', 'Funcionalidad / información priorizada.'],
];

export const EVIDENCIA = [
  ['Establecimientos de carácter comercial', 72.9, '%', 'Comuna 6', 2014, 'Alto', 'INV-008 / caracterización DAP', 'Contexto de estructura de oferta', 'Historico'],
  ['Establecimientos de servicios', 19.2, '%', 'Comuna 6', 2014, 'Alto', 'INV-008 / caracterización DAP', 'Contexto de estructura de oferta', 'Historico'],
  ['Establecimientos industriales', 7.9, '%', 'Comuna 6', 2014, 'Alto', 'INV-008 / caracterización DAP', 'Contexto de estructura de oferta', 'Historico'],
  ['Hogares con algún negocio en la vivienda', 3758, 'hogares', 'Comuna 6', 2015, 'Alto', 'INV-008 / Encuesta de Calidad de Vida', 'Indicador de actividad económica en vivienda', 'Historico'],
  ['Hogares con negocio en vivienda', 7.2, '%', 'Comuna 6', 2015, 'Alto', 'INV-008 / Encuesta de Calidad de Vida', 'Indicador porcentual', 'Historico'],
  ['Participación de empresas de Medellín ubicadas en Comuna 6', 1.9, '%', 'Comuna 6', 2015, 'Alto', 'INV-008 / Cámara de Comercio', 'Estructura empresarial histórica', 'Historico'],
  ['Microempresas de comercio al por menor', 99, '%', 'Comuna 6', 2015, 'Alto', 'INV-008 / Cámara de Comercio', 'Caracterización empresarial histórica', 'Historico'],
  ['Casas de cultura', 4, 'equipamientos', 'Comuna 6', 2015, 'Medio-Alto', 'INV-008', 'Infraestructura cultural documentada', 'Historico'],
  ['Bibliotecas', 5, 'equipamientos', 'Comuna 6', 2015, 'Medio-Alto', 'INV-008', 'Infraestructura cultural documentada', 'Historico'],
  ['Parque biblioteca', 1, 'equipamiento', 'Comuna 6', 2015, 'Medio-Alto', 'INV-008', 'Infraestructura cultural documentada', 'Historico'],
  ['Teatros al aire libre', 3, 'espacios', 'Comuna 6', 2015, 'Medio-Alto', 'INV-008', 'Infraestructura cultural documentada', 'Historico'],
  ['Participación en organización de eventos culturales/recreativos/deportivos', 31.37, '%', 'Medellín', 2023, 'Medio / contexto', 'INV-008 / Encuesta Cultura Ciudadana', 'NO presentarlo como dato de C6', 'Contextual'],
  ['Satisfacción con actividad cultural de la ciudad', 67.5, '%', 'Medellín', 2024, 'Medio / contexto', 'INV-008 / Medellín Cómo Vamos', 'NO presentarlo como dato de C6', 'Contextual'],
  ['Compras online', 62.3, '%', 'Colombia', null, 'Alto / contexto', 'INV-005', 'Tendencia nacional; no demanda C6', 'Contextual'],
  ['Penetración de internet', 73.4, '%', 'Colombia', 2024, 'Alto / contexto', 'INV-005 / DataReportal', 'Tendencia nacional; no demanda C6', 'Contextual'],
  ['Participación cultural', 77, '%', 'Medellín', null, 'Alto / contexto', 'INV-005 / Secretaría de Cultura', 'Tendencia ciudad; no demanda C6', 'Contextual'],
  ['Asistencia a conciertos/festivales musicales', 30, '%', 'Medellín', null, 'Alto / contexto', 'INV-005', 'Tendencia ciudad; no demanda C6', 'Contextual'],
  ['Asistencia a cine/proyecciones', 41, '%', 'Medellín', null, 'Alto / contexto', 'INV-005', 'Tendencia ciudad; no demanda C6', 'Contextual'],
  ['Gasto en comidas fuera del hogar', 4.65, '% del gasto', 'Medellín', 2024, 'Medio / contexto', 'INV-005', 'Contexto gastronómico; no demanda C6', 'Contextual'],
  ['Restaurantes activos en plataformas de domicilios', 2100, '+ restaurantes', 'Medellín', null, 'Medio / contexto', 'INV-005', 'Contexto; no contar como C6', 'Contextual'],
  ['Ventas programa Acceso a Mercados', 9500, 'millones COP +', 'Medellín', 2025, 'Alto / contexto', 'INV-005 / Secretaría Desarrollo Económico', 'Contexto de acceso a mercados', 'Contextual'],
  ['Emprendedores acompañados por Acceso a Mercados', 2137, 'emprendedores', 'Medellín', 2025, 'Alto / contexto', 'INV-005 / Secretaría Desarrollo Económico', 'Contexto de programa', 'Contextual'],
  ['Eventos/espacios comerciales acompañados', 144, 'espacios/eventos', 'Medellín', 2024, 'Alto / contexto', 'INV-005 / Secretaría Desarrollo Económico', 'Contexto de acceso a mercados', 'Contextual'],
  ['Ferias y eventos acompañados', 153, 'eventos', 'Medellín', null, 'Alto / contexto', 'INV-005 / Secretaría Desarrollo Económico', 'Contexto de acceso a mercados', 'Contextual'],
];

export const ACTIVOS = [
  [1, 'Corporación Cultural TallerArte', 'Organización cultural', 'Comuna 6', 2025, 'Alto', 'Alto', 'Medio', 'Medio', 'Alto', '40+ años de trayectoria; reconocimiento institucional; patrimonio cultural documentado; potencial turístico cultural.'],
  [2, 'Fiestas de la Raza', 'Evento / festividad', 'Barrio 12 de Octubre / Comuna 6', 2025, 'Alto', 'Alto', 'Medio', 'Medio', 'Alto', 'Festividad anual consolidada; identidad barrial; cobertura mediática.'],
  [3, 'Corporación Educativa y Cultural Simón Bolívar', 'Organización cultural/comunitaria', 'Comuna 6', 2025, 'Alto', 'Alto', 'Medio', 'Medio', 'Medio', '45+ años de trayectoria; ludoteca, escuela de comunicación, festivales y archivo audiovisual.'],
  [4, 'Medellín Music Lab', 'Programa / formación musical', 'Medellín (incluye relación con C6)', 2025, 'Medio', 'Medio', 'Alto', 'Alto', 'Alto', 'Formación en industria musical; la investigación reporta generación de ingresos y alta visibilidad.'],
  [5, 'Casa de Cultura Pedregal', 'Equipamiento cultural', 'Pedregal / Comuna 6', 2025, 'Alto', 'Alto', 'Medio', 'Medio', 'Alto', 'Equipamiento municipal activo; programación constante; sede de eventos como Convite Barrio y Palabra.'],
  [6, 'Corredores Artísticos Comuna 6', 'Iniciativa / proceso cultural', 'Comuna 6', 2025, 'Alto', 'Alto', 'Bajo', 'Bajo', 'Medio', 'Iniciativa de identidad comunitaria documentada; sin comercialización documentada en la investigación.'],
  [7, 'Kaleidoskopio Compañía de Danza', 'Compañía / colectivo artístico', 'Comuna 6', 2025, 'Medio', 'Medio', 'Medio', 'Medio', 'Medio', 'Formación y producción artística en folclor, baile urbano y danza contemporánea.'],
  [8, 'Aframerindia Colectivo Audiovisual', 'Colectivo cultural', 'Comuna 6', 2025, 'Medio', 'Medio', 'Medio', 'Medio', 'Medio', 'Producción audiovisual con potencial de producción y formación.'],
  [9, 'Festival Urbano Comuna 6', 'Evento cultural', 'Comuna 6', 2025, 'Alto', 'Alto', 'Medio', 'Medio', 'Alto', 'Evento municipal reciente con artistas locales y visibilidad documentada.'],
  [10, 'Corporación Picacho con Futuro', 'Organización comunitaria/cultural', 'Cerro Picacho / Comuna 6', 2025, 'Alto', 'Alto', 'Bajo', 'Bajo', 'Medio', '30+ años de trayectoria y trabajo comunitario en Cerro Picacho.'],
];

export const ESTRUCTURA = [
  ['Establecimientos comerciales', 72.9, '%', 'Comuna 6', 2014, 'INV-008', 'Caracterización histórica de estructura económica.'],
  ['Establecimientos de servicios', 19.2, '%', 'Comuna 6', 2014, 'INV-008', 'Caracterización histórica de estructura económica.'],
  ['Establecimientos industriales', 7.9, '%', 'Comuna 6', 2014, 'INV-008', 'Caracterización histórica de estructura económica.'],
  ['Hogares con negocio en vivienda', 3758, 'hogares', 'Comuna 6', 2015, 'INV-008', '7,2% de hogares; segunda comuna con más negocios en hogar según investigación.'],
  ['Empresas de Medellín ubicadas en Comuna 6', 1.9, '%', 'Comuna 6', 2015, 'INV-008', 'Dato histórico de Cámara de Comercio.'],
  ['Microempresas de comercio al por menor', 99, '%', 'Comuna 6', 2015, 'INV-008', 'Dato histórico de Cámara de Comercio.'],
  ['Activos culturales, comunitarios y territoriales documentados', 50, 'activos (mínimo)', 'Comuna 6', null, 'INV-006', 'Incluye organizaciones, escenarios, eventos, colectivos y programas; requiere validación de vigencia. 50+ reportados por INV-006.'],
];

export const CANALES = [
  ['Google Maps', 'Mapa / buscador', 'Irregular', 'Comercio / servicios', 'Nombre, ubicación, contacto y otros campos según registro', 'Cobertura depende del registro voluntario; no se hizo censo completo; no equivale a cobertura total.', 'INV-007', 'Fuente seleccionable; requiere normalización/verificación'],
  ['Google Search', 'Buscador', 'No determinada', 'Múltiple', 'Permite encontrar páginas, perfiles y publicaciones', 'Resultados dispersos; no ofrece catálogo territorial integrado.', 'INV-002 / INV-007', 'Fuente complementaria'],
  ['Facebook', 'Red social', 'Presencia documentada', 'Emprendimientos / comunidad / oferta local', 'Publicaciones, grupos, perfiles y contacto', 'Información no estructurada y sin taxonomía territorial común.', 'INV-002 / INV-007', 'Fuente complementaria'],
  ['Instagram', 'Red social', 'Presencia documentada', 'Emprendimientos / cultura / comercio', 'Perfiles, publicaciones, contacto', 'Información no estructurada; no hay medición cuantitativa de uso en C6.', 'INV-007', 'Fuente complementaria'],
  ['TikTok', 'Red social', 'Presencia documentada / no cuantificada', 'Oferta / cultura / emprendimientos', 'Contenido audiovisual', 'No existe medición específica de cobertura C6 en investigación.', 'INV-007', 'Fuente complementaria'],
  ['WhatsApp Business', 'Canal de contacto', 'Presencia documentada / no cuantificada', 'Negocios / servicios', 'Contacto y conversión', 'No existe medición específica de cobertura C6.', 'INV-007 / INV-008', 'Campo de catálogo cuando exista'],
  ['Rappi / domicilios', 'Plataforma comercial', 'Parcial / no determinada', 'Gastronomía / comercio', 'Productos, establecimientos y pedidos según plataforma', 'No siempre identifica comuna; no hay dato específico de negocios C6 ni volumen de pedidos.', 'INV-007 / INV-005', 'Fuente complementaria'],
  ['Agendas culturales institucionales', 'Institucional / cultural', 'Parcial', 'Eventos / cultura', 'Eventos, fechas, escenarios', 'Filtrado específico por comuna limitado; publicaciones dispersas.', 'INV-007', 'Fuente prioritaria para eventos'],
  ['Secretaría de Cultura / Alcaldía', 'Institucional', 'Parcial', 'Cultura / eventos / programas', 'Programación, noticias, proyectos', 'Información distribuida entre páginas y publicaciones.', 'INV-002 / INV-007', 'Fuente prioritaria'],
  ['Sistema de Bibliotecas Públicas', 'Institucional / cultural', 'Parcial', 'Bibliotecas / cultura / eventos', 'Programación y equipamientos', 'No integra toda la oferta económica/comercial.', 'INV-007', 'Fuente prioritaria'],
  ['Datos Abiertos Medellín / Colombia', 'Datos abiertos', 'Parcial / variable', 'Empresas / territorio / indicadores', 'Bases y datasets', 'No están diseñados como buscador ciudadano integral y el filtro por comuna puede ser limitado.', 'INV-007', 'Fuente estructurante'],
  ['Cámara de Comercio de Medellín', 'Empresarial / institucional', 'Parcial', 'Empresas formales', 'Información empresarial agregada / registros', 'No cubre necesariamente oferta informal; acceso y desagregación dependen del dataset.', 'INV-004 / INV-007', 'Fuente estructurante'],
  ['DANE', 'Estadística oficial', 'Parcial', 'Empresas / población / territorio', 'Estadísticas y geovisores', 'No entrega toda la oferta territorial a nivel de registro ciudadano.', 'INV-005 / INV-007', 'Fuente contextual/estructurante'],
  ['SIL Comuna 6 / redes comunitarias', 'Comunitario', 'Parcial', 'Información territorial / comunidad', 'Información local y publicaciones', 'No constituye una plataforma oficial integral de oferta.', 'INV-002 / INV-003', 'Fuente complementaria'],
];

export const BRECHAS = [
  ['Cantidad total de negocios activos', 'Comuna 6', 'No disponible públicamente', 'No mostrar total como censo; mostrar solo registros efectivamente catalogados.', 'INV-007', 'Brecha'],
  ['Distribución sectorial completa actual', 'Comuna 6', 'No disponible públicamente', 'No representar como distribución actual si proviene de datos históricos.', 'INV-007', 'Brecha'],
  ['Porcentaje formal vs. informal', 'Comuna 6', 'No disponible', 'No inferir informalidad desde datos nacionales.', 'INV-004 / INV-007', 'Brecha'],
  ['Cobertura exacta de Google Maps', 'Comuna 6', 'No medida', 'No calcular % de negocios presentes en Maps.', 'INV-007', 'Brecha'],
  ['Porcentaje de negocios por red social', 'Comuna 6', 'No disponible', 'No presentar Facebook/Instagram como porcentajes territoriales salvo encuesta de 28 personas.', 'INV-007', 'Brecha'],
  ['Impacto económico de domicilios', 'Comuna 6', 'No disponible', 'No calcular ventas/pedidos de Rappi u otras plataformas para C6.', 'INV-007', 'Brecha'],
  ['Frecuencia de actualización por propietarios', 'Comuna 6', 'No disponible', 'No afirmar periodicidad real de actualización externa.', 'INV-007', 'Brecha'],
  ['Satisfacción con canales actuales antes de la validación', 'Comuna 6', 'No disponible documentalmente', 'La encuesta exploratoria de 28 sí aporta una medición limitada, no representativa.', 'INV-008', 'Brecha + validación'],
  ['Demanda específica de gasto/consumo', 'Comuna 6', 'No disponible públicamente', 'Usar Medellín/Colombia solo como contexto, nunca como demanda C6.', 'INV-005', 'Brecha'],
  ['Comercio electrónico por comuna', 'Comuna 6', 'No disponible', 'No estimar ventas online locales.', 'INV-005', 'Brecha'],
  ['Turismo por Comuna 6', 'Comuna 6', 'No disponible', 'No estimar visitantes/turistas específicos de C6.', 'INV-005', 'Brecha'],
  ['Ventas de productos culturales por Comuna 6', 'Comuna 6', 'No disponible', 'No afirmar ingresos generados por activos culturales locales.', 'INV-004', 'Brecha'],
  ['Adopción de e-commerce / CRM / automatización por MiPymes de C6', 'Comuna 6', 'No disponible', 'No mostrar indicador de transformación digital territorial.', 'INV-004', 'Brecha'],
  ['Tasa de formalización de emprendimientos culturales', 'Comuna 6', 'No disponible', 'No mostrar porcentaje de formalización cultural.', 'INV-004', 'Brecha'],
];

export const CAMPOS_CALIDAD = [
  ['Nombre', 'Identificación del registro', 'Alta', 'INV-007 / INV-006', 'Tabla de registros'],
  ['Categoría', 'Clasificación de oferta', 'Alta', 'INV-007', 'Distribución por categorías'],
  ['Subcategoría', 'Mayor granularidad', 'Media', 'INV-007', 'Filtros'],
  ['Tipo de actor / activo', 'Diferenciar negocio, organización, evento, espacio, activo', 'Alta', 'INV-003 / INV-006', 'Distribución por tipo'],
  ['Descripción', 'Contenido del registro', 'Media', 'INV-007', 'Detalle'],
  ['Ubicación / dirección', 'Localización', 'Alta', 'INV-007', 'Mapa / filtros'],
  ['Barrio', 'Desagregación territorial', 'Alta', 'INV-007', 'Cobertura por barrio'],
  ['Coordenadas', 'Georreferenciación', 'Alta', 'INV-007', 'Mapa'],
  ['Teléfono / WhatsApp', 'Contacto', 'Alta', 'INV-007', 'Accesibilidad/contacto'],
  ['Correo', 'Contacto', 'Media', 'INV-007', 'Detalle'],
  ['Sitio web / redes', 'Presencia digital', 'Media', 'INV-007', 'Indicadores digitales'],
  ['Horario', 'Disponibilidad', 'Alta', 'INV-007', 'Información para consulta'],
  ['Productos / servicios', 'Oferta', 'Alta', 'INV-007', 'Búsqueda / categorías'],
  ['Rango de precios', 'Información para decisión', 'Media', 'INV-007 / INV-008', 'Filtro/consulta cuando exista'],
  ['Fuente', 'Trazabilidad', 'Alta', 'INV-007', '% con fuente'],
  ['URL de fuente', 'Verificación', 'Alta', 'INV-007', 'Acceso a evidencia'],
  ['Fecha de verificación', 'Actualización', 'Alta', 'INV-007', '% actualizado / antigüedad'],
  ['Nivel de confianza', 'Calidad', 'Alta', 'INV-007', 'Indicador de calidad'],
  ['Estado del registro', 'Vigencia / revisión', 'Alta', 'INV-007', 'Pendientes / verificados'],
  ['Fotos', 'Información visual', 'Media', 'INV-007', 'Detalle'],
  ['Etiquetas', 'Búsqueda semántica', 'Media', 'INV-007', 'Búsqueda / filtros'],
];
